### ISSUE TITLE
Part 10\aliens.py

### ISSUE THREAD

**Issue by asnramos** [seanmtracey/Games-with-Pygame#23]
Warning (from warnings module):
  File "C:\python-codigo\Games-with-Pygame-master\Games-with-Pygame-master\Part 10\aliens.py", line 65
    if enemyAtThisPosition is 1:
SyntaxWarning: "is" with a literal. Did you mean "=="?
>>> 
Warning (from warnings module):
  File "C:\python-codigo\Games-with-Pygame-master\Games-with-Pygame-master\Part 10\aliens.py", line 83
    if mouseStates[0] is 1 and mouseDown is False:
SyntaxWarning: "is" with a literal. Did you mean "=="?
>>> 
Warning (from warnings module):
  File "C:\python-codigo\Games-with-Pygame-master\Games-with-Pygame-master\Part 10\aliens.py", line 86
    elif mouseStates[0] is 0 and mouseDown is True:
SyntaxWarning: "is" with a literal. Did you mean "=="?
>>> 
Warning (from warnings module):
  File "C:\python-codigo\Games-with-Pygame-master\Games-with-Pygame-master\Part 10\aliens.py", line 194
    if mouseStates[0] is 1:
SyntaxWarning: "is" with a literal. Did you mean "=="?
>>> 
Warning (from warnings module):
  File "C:\python-codigo\Games-with-Pygame-master\Games-with-Pygame-master\Part 10\aliens.py", line 200
    elif mouseStates[0] is 0 and mouseDown is True:
SyntaxWarning: "is" with a literal. Did you mean "=="?
>>> 
Warning (from warnings module):
  File "C:\python-codigo\Games-with-Pygame-master\Games-with-Pygame-master\Part 10\aliens.py", line 207
    if gameStarted is True and gameWon is True and len(enemyShips) is 0:
SyntaxWarning: "is" with a literal. Did you mean "=="?

**Comment by milohax** [comment]
This warning about '"is" with a literal' a bit confusing. _Technically_ you may ignore it, but I'll discuss what it actually means.

1. The `aliens.py` code makes use of Python's [is operator](https://docs.python.org/3/reference/expressions.html#is) rather than the `==` "is equal to" [comparator](https://docs.python.org/3/library/stdtypes.html#comparisons), presumably because this makes for a nice English-like expression:   `enemyAtThisPosition is 1`
2. What `is` is comparing is that the _identity_ of `enemyAtThisPosition` is the same as the _identity_ of the literal number `1`
3. For Numbers, and Booleans (`True` and `False`), this is fine to do, but _not always_ for String values, which is why Python is warning us (even though we aren't comparing Strings)

So, what is this _identity_, and why is it not always "safe" to test it for Strings?

Well, the identity is best understood as a concept of _the actual thing_ being looked at. In a computer, it's _the actual place in memory of the thing_.  Python will automatically consider all numbers to be _the same actual numbers_ (all `1`s are _the same `1`_, all `True`ths are _the same_).

So `enemyAtThisPosition is 1` is not _exactly_ the same as saing `enemyAtThisPosition == 1`.  Here, we test that `enemyAtThisPosition` has the _same value_ as `1`. But in Python `enemyAtThisPosition` also _is_  the number `1`.

But this distinction is so pedantic as to be confusing.

For Strings, though (and other Objects), you can't say `'apple' is 'apple'` and expect `True`. They _could_ be two different Strings, with the same value. They are _equal_ still, but not _the same_.

You can [intern](https://docs.python.org/3/library/sys.html#sys.intern) a String, for a performance boost, so that there _is_ only one instance of a String: the String and the literal strings in the code are _the same string_, but you won't avoid the warning.
